//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Football/Input/FootballInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @FootballInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @FootballInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""FootballInput"",
    ""maps"": [
        {
            ""name"": ""Gloves"",
            ""id"": ""3342b524-2dd5-4315-bd40-78d597440612"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""29096a38-63b1-4d00-b160-03ee4548530b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""897f0507-22b6-4829-b4dd-35a9a7726c40"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d21b9bcb-93f2-4fda-8424-b5e4d164edb4"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce5152c0-99fc-41b4-b087-53a395bd9986"",
                    ""path"": ""<Mouse>/position/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gloves
        m_Gloves = asset.FindActionMap("Gloves", throwIfNotFound: true);
        m_Gloves_Move = m_Gloves.FindAction("Move", throwIfNotFound: true);
        m_Gloves_Position = m_Gloves.FindAction("Position", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gloves
    private readonly InputActionMap m_Gloves;
    private IGlovesActions m_GlovesActionsCallbackInterface;
    private readonly InputAction m_Gloves_Move;
    private readonly InputAction m_Gloves_Position;
    public struct GlovesActions
    {
        private @FootballInput m_Wrapper;
        public GlovesActions(@FootballInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Gloves_Move;
        public InputAction @Position => m_Wrapper.m_Gloves_Position;
        public InputActionMap Get() { return m_Wrapper.m_Gloves; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GlovesActions set) { return set.Get(); }
        public void SetCallbacks(IGlovesActions instance)
        {
            if (m_Wrapper.m_GlovesActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_GlovesActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GlovesActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GlovesActionsCallbackInterface.OnMove;
                @Position.started -= m_Wrapper.m_GlovesActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_GlovesActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_GlovesActionsCallbackInterface.OnPosition;
            }
            m_Wrapper.m_GlovesActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
            }
        }
    }
    public GlovesActions @Gloves => new GlovesActions(this);
    public interface IGlovesActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnPosition(InputAction.CallbackContext context);
    }
}
