//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Input/SprinkleMover.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SprinkleMover : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SprinkleMover()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SprinkleMover"",
    ""maps"": [
        {
            ""name"": ""Move"",
            ""id"": ""d4709572-21de-4e58-9d5b-6672fc5d2893"",
            ""actions"": [
                {
                    ""name"": ""deltaX"",
                    ""type"": ""Value"",
                    ""id"": ""7d1c5469-29f6-4790-9826-67aa2c3d5c84"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""deltaY"",
                    ""type"": ""Value"",
                    ""id"": ""ff9fedf9-a90e-47a3-8bbe-90732c49125b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bd9de8cc-254c-4f20-a5ab-87528faf55ab"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""deltaX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d38b30c-acf5-4e01-8dc7-ce46a2b43052"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""deltaY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Move
        m_Move = asset.FindActionMap("Move", throwIfNotFound: true);
        m_Move_deltaX = m_Move.FindAction("deltaX", throwIfNotFound: true);
        m_Move_deltaY = m_Move.FindAction("deltaY", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Move
    private readonly InputActionMap m_Move;
    private IMoveActions m_MoveActionsCallbackInterface;
    private readonly InputAction m_Move_deltaX;
    private readonly InputAction m_Move_deltaY;
    public struct MoveActions
    {
        private @SprinkleMover m_Wrapper;
        public MoveActions(@SprinkleMover wrapper) { m_Wrapper = wrapper; }
        public InputAction @deltaX => m_Wrapper.m_Move_deltaX;
        public InputAction @deltaY => m_Wrapper.m_Move_deltaY;
        public InputActionMap Get() { return m_Wrapper.m_Move; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoveActions set) { return set.Get(); }
        public void SetCallbacks(IMoveActions instance)
        {
            if (m_Wrapper.m_MoveActionsCallbackInterface != null)
            {
                @deltaX.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnDeltaX;
                @deltaX.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnDeltaX;
                @deltaX.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnDeltaX;
                @deltaY.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnDeltaY;
                @deltaY.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnDeltaY;
                @deltaY.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnDeltaY;
            }
            m_Wrapper.m_MoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @deltaX.started += instance.OnDeltaX;
                @deltaX.performed += instance.OnDeltaX;
                @deltaX.canceled += instance.OnDeltaX;
                @deltaY.started += instance.OnDeltaY;
                @deltaY.performed += instance.OnDeltaY;
                @deltaY.canceled += instance.OnDeltaY;
            }
        }
    }
    public MoveActions @Move => new MoveActions(this);
    public interface IMoveActions
    {
        void OnDeltaX(InputAction.CallbackContext context);
        void OnDeltaY(InputAction.CallbackContext context);
    }
}
